java -jar wire-mock/wiremock-standalone-2.27.2.jar ^
--port 8888 ^
--verbose ^
::--disable-http ^
::--https-port ^
::--bind-address ^
::--https-keystore ^
::--keystore-type ^
::--keystore-password ^
::--key-manager-password ^
::--https-truststore ^
::--keystore-type ^
::--truststore-password ^
::--https-require-client-cert ^
::--root-dir
::--record-mappings ^
::--match-headers ^
::--proxy-all ^
::--preserve-host-header ^
::--proxy-via ^
::--enable-browser-proxying ^
::--ca-keystore ^
::--ca-keystore-password ^
::--ca-keystore-type ^
::--trust-all-proxy-targets ^
::--trust-proxy-target ^
::--no-request-journal ^
::--container-threads ^
::--max-request-journal-entries ^
::--jetty-acceptor-threads ^
::--jetty-accept-queue-size ^
::--jetty-header-buffer-size ^
::--async-response-enabled ^
::--async-response-threads ^
::--extensions ^
::--print-all-network-traffic ^
::--global-response-templating ^
::--local-response-templating ^
::--max-template-cache-entries ^
::--use-chunked-encoding ^
::--disable-gzip ^
::--disable-request-logging ^
::--permitted-system-keys ^
::--enable-stub-cors ^
::--help ^